export const types = {
  COLLECTION_NEW: 'COLLECTION_NEW',
  COLLECTION_ACTIVE: 'COLLECTION_ACTIVE',
  COLLECTION_LOAD: 'COLLECTION_LOAD',
  COLLECTION_UPDATE: 'COLLECTION_UPDATE',
  COLLECTION_DELETE: 'COLLECTION_DELETE',
}